apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-flask
  name: svc-flask
  namespace: default
spec:
  ports:
    - name: "svc-flask"
      nodePort: 30000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: flask
  type: NodePort
